### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by richiepreece** [UnicycleDumpTruck/MissionControl#2]
Is there any way to get the audio assets into the repository?

Thanks!

**Comment by technoj** [comment]
Most of them are on Freesound.org.

**Comment by richiepreece** [comment]
Awesome. Thanks!

**Comment by technoj** [comment]
You can also take a headphone cable, plug one end into the headphone jack on your computer, and the other end into the microphone jack.  Use GarageBand to record it from this video: http://makezine.com/video/making-fun-mission-control-desk/
